"""ML-Based Failure Predictor from Infrastructure Metrics.

Predicts upcoming component failures from current metric observations
using logistic regression trained on synthetic simulation data.

This covers the 'real infrastructure + ML prediction' approach,
using FaultRay's own simulation results as training data in lieu
of real monitoring data.

Uses ONLY the Python standard library + math + random.
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass, field

from faultray.model.components import Component, ComponentType, HealthStatus
from faultray.model.graph import InfraGraph
from faultray.simulator.cascade import CascadeEngine
from faultray.simulator.scenarios import Fault, FaultType


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass
class MetricObservation:
    """A single metric snapshot for a component."""

    component_id: str
    cpu: float
    memory: float
    disk: float
    connections: int
    timestamp: float = 0.0


@dataclass
class FailurePrediction:
    """Prediction for a single component's upcoming failure."""

    component_id: str
    failure_probability: float
    time_to_failure_minutes: float
    risk_level: str  # "critical", "high", "medium", "low"


@dataclass
class PredictorReport:
    """Aggregated prediction report for the whole infrastructure."""

    predictions: list[FailurePrediction] = field(default_factory=list)
    high_risk_components: list[str] = field(default_factory=list)
    model_accuracy: float = 0.0


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _sigmoid(x: float) -> float:
    x = max(-500.0, min(500.0, x))
    return 1.0 / (1.0 + math.exp(-x))


def _dot(a: list[float], b: list[float]) -> float:
    return sum(ai * bi for ai, bi in zip(a, b))


_FEATURE_DIM = 5  # cpu, mem, disk, connections_norm, utilization_norm


# ---------------------------------------------------------------------------
# ML Failure Predictor
# ---------------------------------------------------------------------------

class MLFailurePredictor:
    """Logistic regression model that predicts component failures from metrics.

    The model is trained on synthetic data generated by running the
    ``CascadeEngine`` on the current ``InfraGraph`` with small random
    perturbations to component metrics.  Components that end up DOWN
    in the simulation are labelled as failures.

    Example usage::

        graph = InfraGraph.load(Path("infra.json"))
        predictor = MLFailurePredictor(graph)
        predictor.train()
        report = predictor.predict_all()
        for p in report.predictions:
            print(f"{p.component_id}: {p.failure_probability:.2%} "
                  f"({p.risk_level}, TTF ~{p.time_to_failure_minutes:.0f}m)")
    """

    def __init__(self, graph: InfraGraph) -> None:
        self.graph = graph

        # Logistic regression parameters: w (weights) and b (bias)
        self._weights: list[float] = [random.gauss(0, 0.1) for _ in range(_FEATURE_DIM)]
        self._bias: float = 0.0

        self._trained = False
        self._accuracy: float = 0.0

    # ------------------------------------------------------------------
    # Feature extraction
    # ------------------------------------------------------------------

    def _extract_features(self, component: Component) -> list[float]:
        """Extract a normalised 5-dim feature vector from component metrics.

        Layout: [cpu/100, mem/100, disk/100, connections/max_connections, utilization/100]
        """
        max_conn = max(component.capacity.max_connections, 1)
        return [
            component.metrics.cpu_percent / 100.0,
            component.metrics.memory_percent / 100.0,
            component.metrics.disk_percent / 100.0,
            min(component.metrics.network_connections / max_conn, 1.0),
            component.utilization() / 100.0,
        ]

    # ------------------------------------------------------------------
    # Training data generation
    # ------------------------------------------------------------------

    def _generate_training_data(
        self, n_samples: int = 500
    ) -> tuple[list[list[float]], list[float]]:
        """Generate labelled training data via CascadeEngine simulations.

        For each sample:
        1. Pick a random component.
        2. Create a perturbed copy of its metrics (small random noise).
        3. Run a CascadeEngine simulation with a random fault on it.
        4. Label = 1.0 if the component ended up DOWN, else 0.0.

        Returns (features_list, labels_list).
        """
        cascade_engine = CascadeEngine(self.graph)
        component_ids = list(self.graph.components.keys())
        if not component_ids:
            return [], []

        fault_types = [
            FaultType.COMPONENT_DOWN,
            FaultType.CPU_SATURATION,
            FaultType.MEMORY_EXHAUSTION,
            FaultType.DISK_FULL,
            FaultType.CONNECTION_POOL_EXHAUSTION,
        ]

        all_features: list[list[float]] = []
        all_labels: list[float] = []

        for _ in range(n_samples):
            target_id = random.choice(component_ids)
            comp = self.graph.components[target_id]

            # Perturb metrics slightly to create training variety
            perturbed_features = self._extract_features(comp)
            perturbed_features = [
                max(0.0, min(1.0, f + random.gauss(0, 0.15)))
                for f in perturbed_features
            ]

            # Run simulation to determine label
            fault_type = random.choice(fault_types)
            fault = Fault(
                target_component_id=target_id,
                fault_type=fault_type,
            )
            chain = cascade_engine.simulate_fault(fault)

            # Check if the target ended up DOWN
            label = 0.0
            for effect in chain.effects:
                if effect.component_id == target_id and effect.health == HealthStatus.DOWN:
                    label = 1.0
                    break

            # Use the (possibly high-stress) perturbed features for positive samples
            if label == 1.0:
                # Bias features toward high utilisation for failures
                stress_features = [
                    max(0.0, min(1.0, f + random.uniform(0.1, 0.4)))
                    for f in perturbed_features
                ]
                all_features.append(stress_features)
            else:
                # For non-failures, use normal or slightly perturbed features
                normal_features = [
                    max(0.0, min(1.0, f - random.uniform(0.0, 0.2)))
                    for f in perturbed_features
                ]
                all_features.append(normal_features)

            all_labels.append(label)

        return all_features, all_labels

    # ------------------------------------------------------------------
    # Training
    # ------------------------------------------------------------------

    def train(self, epochs: int = 200, lr: float = 0.01) -> None:
        """Train the logistic regression model using SGD.

        Uses binary cross-entropy loss:
            L = -[y * log(p) + (1-y) * log(1-p)]
        Gradient w.r.t. weights:
            dL/dw = (p - y) * x
        """
        features, labels = self._generate_training_data()
        if not features:
            return

        n = len(features)

        for _epoch in range(epochs):
            # Shuffle training data
            indices = list(range(n))
            random.shuffle(indices)

            for i in indices:
                x = features[i]
                y = labels[i]

                # Forward
                logit = _dot(self._weights, x) + self._bias
                p = _sigmoid(logit)

                # Gradient: (p - y) * x_k for each weight
                error = p - y
                for k in range(_FEATURE_DIM):
                    self._weights[k] -= lr * error * x[k]
                self._bias -= lr * error

        # Evaluate accuracy on training data
        correct = 0
        for i in range(n):
            x = features[i]
            y = labels[i]
            logit = _dot(self._weights, x) + self._bias
            p = _sigmoid(logit)
            predicted = 1.0 if p >= 0.5 else 0.0
            if predicted == y:
                correct += 1

        self._accuracy = correct / max(n, 1)
        self._trained = True

    # ------------------------------------------------------------------
    # Prediction
    # ------------------------------------------------------------------

    def predict(self, component: Component) -> FailurePrediction:
        """Predict failure probability for a single component.

        Args:
            component: The infrastructure component to assess.

        Returns:
            FailurePrediction with probability, estimated TTF, and risk level.
        """
        features = self._extract_features(component)
        logit = _dot(self._weights, features) + self._bias
        prob = _sigmoid(logit)

        # Estimate time to failure based on current utilisation trend
        utilisation = component.utilization()
        if prob > 0.8:
            ttf_minutes = max(1.0, (1.0 - utilisation / 100.0) * 60.0)
        elif prob > 0.5:
            ttf_minutes = max(10.0, (1.0 - utilisation / 100.0) * 360.0)
        else:
            ttf_minutes = max(60.0, (1.0 - utilisation / 100.0) * 1440.0)

        # Risk level
        if prob >= 0.8:
            risk_level = "critical"
        elif prob >= 0.6:
            risk_level = "high"
        elif prob >= 0.3:
            risk_level = "medium"
        else:
            risk_level = "low"

        return FailurePrediction(
            component_id=component.id,
            failure_probability=round(prob, 4),
            time_to_failure_minutes=round(ttf_minutes, 1),
            risk_level=risk_level,
        )

    def predict_all(self) -> PredictorReport:
        """Predict failure probability for all components in the graph.

        Returns a PredictorReport sorted by failure probability descending.
        """
        predictions: list[FailurePrediction] = []

        for comp in self.graph.components.values():
            pred = self.predict(comp)
            predictions.append(pred)

        # Sort by failure probability descending
        predictions.sort(key=lambda p: p.failure_probability, reverse=True)

        high_risk = [
            p.component_id for p in predictions
            if p.risk_level in ("critical", "high")
        ]

        return PredictorReport(
            predictions=predictions,
            high_risk_components=high_risk,
            model_accuracy=self._accuracy,
        )

    def evaluate(
        self,
        test_data: tuple[list[list[float]], list[float]] | None = None,
    ) -> dict:
        """Evaluate model performance on test data.

        If no test_data is provided, generates a fresh test set.

        Returns dict with accuracy, precision, recall.
        """
        if test_data is None:
            features, labels = self._generate_training_data(n_samples=100)
        else:
            features, labels = test_data

        if not features:
            return {"accuracy": 0.0, "precision": 0.0, "recall": 0.0}

        tp = fp = tn = fn = 0

        for i in range(len(features)):
            x = features[i]
            y = labels[i]
            logit = _dot(self._weights, x) + self._bias
            p = _sigmoid(logit)
            predicted = 1.0 if p >= 0.5 else 0.0

            if predicted == 1.0 and y == 1.0:
                tp += 1
            elif predicted == 1.0 and y == 0.0:
                fp += 1
            elif predicted == 0.0 and y == 0.0:
                tn += 1
            else:
                fn += 1

        total = tp + fp + tn + fn
        accuracy = (tp + tn) / max(total, 1)
        precision = tp / max(tp + fp, 1)
        recall = tp / max(tp + fn, 1)

        return {
            "accuracy": round(accuracy, 4),
            "precision": round(precision, 4),
            "recall": round(recall, 4),
        }
