# Copyright (c) 2025-2026 Yutaro Maeda. All rights reserved.
# Licensed under the Apache License 2.0. See LICENSE file for details.

"""Terraform Generator: InfraGraph + RequirementsSpecからTerraform HCLを生成する。

Terraform best practices準拠:
- リソースごとにファイル分割
- variables.tf / outputs.tf / provider.tf / vpc.tf / security.tf
- 命名規則: {project}-{role}-{env}
"""

from __future__ import annotations

import re
import textwrap
from dataclasses import dataclass, field

from faultray.autopilot.requirements_parser import RequirementsSpec
from faultray.model.components import Component, ComponentType
from faultray.model.graph import InfraGraph


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class TerraformOutput:
    """Result of Terraform generation."""

    files: dict[str, str] = field(default_factory=dict)   # filename → HCL content
    warnings: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------


def _tf_name(s: str) -> str:
    """Convert a string to a valid Terraform resource name."""
    return re.sub(r"[^a-zA-Z0-9_]", "_", s).strip("_").lower()


def _hcl_escape(s: str) -> str:
    """Escape a string for safe embedding in HCL double-quoted strings."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _indent(text: str, spaces: int = 2) -> str:
    return textwrap.indent(textwrap.dedent(text).strip(), " " * spaces)


# ---------------------------------------------------------------------------
# TerraformGenerator
# ---------------------------------------------------------------------------


class TerraformGenerator:
    """Generate Terraform HCL from InfraGraph + RequirementsSpec."""

    def generate(self, graph: InfraGraph, spec: RequirementsSpec) -> TerraformOutput:
        """Generate all Terraform files. Returns TerraformOutput."""
        result = TerraformOutput()
        project = _tf_name(spec.app_name)

        result.files["provider.tf"] = self._generate_provider(spec, project)
        result.files["variables.tf"] = self._generate_variables(spec, project)
        result.files["vpc.tf"] = self._generate_vpc(spec, project)
        result.files["security.tf"] = self._generate_security_groups(graph, spec, project)
        result.files["outputs.tf"] = self._generate_outputs(graph, spec, project)

        # Resolve DB and LB component safe names once for shared references
        db_safe = self._find_component_safe(graph, ComponentType.DATABASE)
        lb_safe = self._find_component_safe(graph, ComponentType.LOAD_BALANCER)

        # Generate iam.tf once (shared by all ECS components)
        has_app_server = any(
            c.type == ComponentType.APP_SERVER for c in graph.components.values()
        )
        if has_app_server:
            result.files["iam.tf"] = self._gen_iam(project)

        for comp in graph.components.values():
            filename, content = self._generate_component_file(
                comp, spec, project, db_safe=db_safe, lb_safe=lb_safe
            )
            if content:
                result.files[filename] = content
            else:
                result.warnings.append(
                    f"Component '{comp.id}' (type={comp.type.value}) has no Terraform mapping."
                )

        return result

    @staticmethod
    def _find_component_safe(graph: InfraGraph, ctype: ComponentType) -> str | None:
        """Return the Terraform-safe name of the first component of *ctype*, or None."""
        for comp in graph.components.values():
            if comp.type == ctype:
                # CloudFront is LOAD_BALANCER but is not the ALB target
                if ctype == ComponentType.LOAD_BALANCER and "cloudfront" in comp.id.lower():
                    continue
                return _tf_name(comp.id)
        return None

    # ------------------------------------------------------------------
    # provider.tf
    # ------------------------------------------------------------------

    def _generate_provider(self, spec: RequirementsSpec, project: str) -> str:
        safe_app_name = _hcl_escape(spec.app_name)
        return f"""\
# Generated by FaultRay Autopilot
# Project: {safe_app_name}

terraform {{
  required_version = ">= 1.5"

  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}

  backend "s3" {{
    bucket         = "${{var.terraform_state_bucket}}"
    key            = "{project}/terraform.tfstate"
    region         = var.aws_region
    encrypt        = true
    dynamodb_table = "${{var.terraform_lock_table}}"
  }}
}}

provider "aws" {{
  region = var.aws_region

  default_tags {{
    tags = {{
      Project     = var.project_name
      Environment = var.environment
      ManagedBy   = "terraform"
      GeneratedBy = "faultray-autopilot"
    }}
  }}
}}
"""

    # ------------------------------------------------------------------
    # variables.tf
    # ------------------------------------------------------------------

    def _generate_variables(self, spec: RequirementsSpec, project: str) -> str:
        safe_region = _hcl_escape(spec.region)
        safe_app_name = _hcl_escape(spec.app_name)
        return f"""\
# Generated by FaultRay Autopilot

variable "aws_region" {{
  description = "AWS region to deploy resources"
  type        = string
  default     = "{safe_region}"
}}

variable "project_name" {{
  description = "Project name used for resource naming"
  type        = string
  default     = "{safe_app_name}"
}}

variable "environment" {{
  description = "Deployment environment (production, staging, development)"
  type        = string
  default     = "production"
}}

variable "availability_zones" {{
  description = "List of AZs to use for multi-AZ deployment"
  type        = list(string)
  default     = ["{safe_region}a", "{safe_region}c"]
}}

variable "terraform_state_bucket" {{
  description = "S3 bucket for Terraform state"
  type        = string
}}

variable "terraform_lock_table" {{
  description = "DynamoDB table for Terraform state locking"
  type        = string
  default     = "terraform-lock"
}}

variable "vpc_cidr" {{
  description = "CIDR block for the VPC"
  type        = string
  default     = "10.0.0.0/16"
}}

variable "app_instance_type" {{
  description = "EC2 / ECS task size"
  type        = string
  default     = "{self._instance_type(spec)}"
}}

variable "db_instance_class" {{
  description = "RDS instance class"
  type        = string
  default     = "{self._db_instance_class(spec)}"
}}
"""

    def _instance_type(self, spec: RequirementsSpec) -> str:
        scale_map = {
            "low": "t3.small",
            "medium": "t3.medium",
            "high": "t3.large",
            "very_high": "t3.xlarge",
        }
        return scale_map.get(spec.traffic_scale, "t3.medium")

    def _db_instance_class(self, spec: RequirementsSpec) -> str:
        scale_map = {
            "low": "db.t3.micro",
            "medium": "db.t3.medium",
            "high": "db.t3.large",
            "very_high": "db.r6g.large",
        }
        return scale_map.get(spec.traffic_scale, "db.t3.medium")

    # ------------------------------------------------------------------
    # vpc.tf
    # ------------------------------------------------------------------

    def _generate_vpc(self, spec: RequirementsSpec, project: str) -> str:
        az_count = 2 if spec.multi_az else 1

        return f"""\
# Generated by FaultRay Autopilot — VPC & Networking

resource "aws_vpc" "{project}_vpc" {{
  cidr_block           = var.vpc_cidr
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {{
    Name = "${{var.project_name}}-vpc"
  }}
}}

# Public subnets (ALB, NAT GW)
resource "aws_subnet" "{project}_public" {{
  count             = {az_count}
  vpc_id            = aws_vpc.{project}_vpc.id
  cidr_block        = cidrsubnet(var.vpc_cidr, 8, count.index)
  availability_zone = var.availability_zones[count.index]

  map_public_ip_on_launch = true

  tags = {{
    Name = "${{var.project_name}}-public-${{count.index + 1}}"
    Tier = "public"
  }}
}}

# Private subnets (app servers, databases)
resource "aws_subnet" "{project}_private" {{
  count             = {az_count}
  vpc_id            = aws_vpc.{project}_vpc.id
  cidr_block        = cidrsubnet(var.vpc_cidr, 8, count.index + {az_count})
  availability_zone = var.availability_zones[count.index]

  tags = {{
    Name = "${{var.project_name}}-private-${{count.index + 1}}"
    Tier = "private"
  }}
}}

# Database subnets (isolated)
resource "aws_subnet" "{project}_db" {{
  count             = {az_count}
  vpc_id            = aws_vpc.{project}_vpc.id
  cidr_block        = cidrsubnet(var.vpc_cidr, 8, count.index + {az_count * 2})
  availability_zone = var.availability_zones[count.index]

  tags = {{
    Name = "${{var.project_name}}-db-${{count.index + 1}}"
    Tier = "database"
  }}
}}

resource "aws_internet_gateway" "{project}_igw" {{
  vpc_id = aws_vpc.{project}_vpc.id

  tags = {{
    Name = "${{var.project_name}}-igw"
  }}
}}

resource "aws_eip" "{project}_nat" {{
  count  = {az_count}
  domain = "vpc"
}}

resource "aws_nat_gateway" "{project}_nat" {{
  count         = {az_count}
  allocation_id = aws_eip.{project}_nat[count.index].id
  subnet_id     = aws_subnet.{project}_public[count.index].id

  tags = {{
    Name = "${{var.project_name}}-nat-${{count.index + 1}}"
  }}
}}

resource "aws_route_table" "{project}_public_rt" {{
  vpc_id = aws_vpc.{project}_vpc.id

  route {{
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.{project}_igw.id
  }}

  tags = {{
    Name = "${{var.project_name}}-public-rt"
  }}
}}

resource "aws_route_table" "{project}_private_rt" {{
  count  = {az_count}
  vpc_id = aws_vpc.{project}_vpc.id

  route {{
    cidr_block     = "0.0.0.0/0"
    nat_gateway_id = aws_nat_gateway.{project}_nat[count.index].id
  }}

  tags = {{
    Name = "${{var.project_name}}-private-rt-${{count.index + 1}}"
  }}
}}

resource "aws_route_table_association" "{project}_public_rta" {{
  count          = {az_count}
  subnet_id      = aws_subnet.{project}_public[count.index].id
  route_table_id = aws_route_table.{project}_public_rt.id
}}

resource "aws_route_table_association" "{project}_private_rta" {{
  count          = {az_count}
  subnet_id      = aws_subnet.{project}_private[count.index].id
  route_table_id = aws_route_table.{project}_private_rt[count.index].id
}}

resource "aws_db_subnet_group" "{project}_db_subnet_group" {{
  name       = "${{var.project_name}}-db-subnet-group"
  subnet_ids = aws_subnet.{project}_db[*].id

  tags = {{
    Name = "${{var.project_name}}-db-subnet-group"
  }}
}}
"""

    # ------------------------------------------------------------------
    # security.tf
    # ------------------------------------------------------------------

    def _generate_security_groups(
        self, graph: InfraGraph, spec: RequirementsSpec, project: str
    ) -> str:
        has_alb = any(c.type == ComponentType.LOAD_BALANCER for c in graph.components.values())
        has_db = any(c.type == ComponentType.DATABASE for c in graph.components.values())
        has_cache = any(c.type == ComponentType.CACHE for c in graph.components.values())

        blocks: list[str] = ["# Generated by FaultRay Autopilot — Security Groups\n"]

        # ALB SG
        if has_alb:
            blocks.append(f"""\
resource "aws_security_group" "{project}_alb_sg" {{
  name        = "${{var.project_name}}-alb-sg"
  description = "Security group for Application Load Balancer"
  vpc_id      = aws_vpc.{project}_vpc.id

  ingress {{
    description = "HTTPS from internet"
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }}

  ingress {{
    description = "HTTP redirect"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }}

  egress {{
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }}

  tags = {{
    Name = "${{var.project_name}}-alb-sg"
  }}
}}
""")

        # App SG
        blocks.append(f"""\
resource "aws_security_group" "{project}_app_sg" {{
  name        = "${{var.project_name}}-app-sg"
  description = "Security group for application servers"
  vpc_id      = aws_vpc.{project}_vpc.id

  ingress {{
    description     = "From ALB"
    from_port       = 0
    to_port         = 65535
    protocol        = "tcp"
    security_groups = [{f'aws_security_group.{project}_alb_sg.id' if has_alb else '""'}]
  }}

  egress {{
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }}

  tags = {{
    Name = "${{var.project_name}}-app-sg"
  }}
}}
""")

        # DB SG
        if has_db:
            blocks.append(f"""\
resource "aws_security_group" "{project}_db_sg" {{
  name        = "${{var.project_name}}-db-sg"
  description = "Security group for database"
  vpc_id      = aws_vpc.{project}_vpc.id

  ingress {{
    description     = "From app servers"
    from_port       = 5432
    to_port         = 5432
    protocol        = "tcp"
    security_groups = [aws_security_group.{project}_app_sg.id]
  }}

  egress {{
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }}

  tags = {{
    Name = "${{var.project_name}}-db-sg"
  }}
}}
""")

        # Cache SG
        if has_cache:
            blocks.append(f"""\
resource "aws_security_group" "{project}_cache_sg" {{
  name        = "${{var.project_name}}-cache-sg"
  description = "Security group for ElastiCache"
  vpc_id      = aws_vpc.{project}_vpc.id

  ingress {{
    description     = "Redis from app servers"
    from_port       = 6379
    to_port         = 6379
    protocol        = "tcp"
    security_groups = [aws_security_group.{project}_app_sg.id]
  }}

  egress {{
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }}

  tags = {{
    Name = "${{var.project_name}}-cache-sg"
  }}
}}
""")

        return "\n".join(blocks)

    # ------------------------------------------------------------------
    # outputs.tf
    # ------------------------------------------------------------------

    def _generate_outputs(
        self, graph: InfraGraph, spec: RequirementsSpec, project: str
    ) -> str:
        lines: list[str] = ["# Generated by FaultRay Autopilot — Outputs\n"]

        for comp in graph.components.values():
            safe = _tf_name(comp.id)
            if comp.type == ComponentType.LOAD_BALANCER and "cloudfront" not in comp.id:
                lines.append(f"""\
output "{safe}_dns_name" {{
  description = "DNS name of {comp.name}"
  value       = aws_lb.{project}_{safe}.dns_name
}}
""")
            elif comp.type == ComponentType.DATABASE:
                lines.append(f"""\
output "{safe}_endpoint" {{
  description = "Endpoint of {comp.name}"
  value       = aws_db_instance.{project}_{safe}.endpoint
  sensitive   = true
}}
""")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Component file generation
    # ------------------------------------------------------------------

    def _generate_component_file(
        self,
        comp: Component,
        spec: RequirementsSpec,
        project: str,
        db_safe: str | None = None,
        lb_safe: str | None = None,
    ) -> tuple[str, str]:
        """Return (filename, hcl_content) for a component."""
        safe = _tf_name(comp.id)

        if comp.type == ComponentType.LOAD_BALANCER:
            if "cloudfront" in comp.id.lower():
                return f"{safe}.tf", self._gen_cloudfront(
                    comp, spec, project, safe, lb_safe=lb_safe
                )
            return f"{safe}.tf", self._gen_alb(comp, spec, project, safe)

        if comp.type == ComponentType.DATABASE:
            return f"{safe}.tf", self._gen_rds(comp, spec, project, safe)

        if comp.type == ComponentType.CACHE:
            return f"{safe}.tf", self._gen_elasticache(comp, spec, project, safe)

        if comp.type == ComponentType.APP_SERVER:
            return f"{safe}.tf", self._gen_ecs(
                comp, spec, project, safe, db_safe=db_safe, lb_safe=lb_safe
            )

        if comp.type == ComponentType.WEB_SERVER:
            # Static frontend → S3 + optional ECS
            return f"{safe}.tf", self._gen_s3_frontend(comp, spec, project, safe)

        if comp.type == ComponentType.QUEUE:
            return f"{safe}.tf", self._gen_sqs(comp, spec, project, safe)

        if comp.type == ComponentType.STORAGE:
            return f"{safe}.tf", self._gen_s3(comp, spec, project, safe)

        return "", ""  # unsupported

    # ------------------------------------------------------------------
    # Resource generators
    # ------------------------------------------------------------------

    def _gen_alb(
        self, comp: Component, spec: RequirementsSpec, project: str, safe: str
    ) -> str:
        internal = "false"
        return f"""\
# Generated by FaultRay Autopilot — ALB

resource "aws_lb" "{project}_{safe}" {{
  name               = "${{var.project_name}}-alb"
  internal           = {internal}
  load_balancer_type = "application"
  security_groups    = [aws_security_group.{project}_alb_sg.id]
  subnets            = aws_subnet.{project}_public[*].id

  enable_deletion_protection = true
  enable_http2               = true

  access_logs {{
    bucket  = "${{var.project_name}}-alb-logs"
    enabled = true
  }}

  tags = {{
    Name = "${{var.project_name}}-alb"
  }}
}}

resource "aws_lb_listener" "{project}_{safe}_https" {{
  load_balancer_arn = aws_lb.{project}_{safe}.arn
  port              = "443"
  protocol          = "HTTPS"
  ssl_policy        = "ELBSecurityPolicy-TLS13-1-2-2021-06"

  default_action {{
    type             = "forward"
    target_group_arn = aws_lb_target_group.{project}_{safe}_tg.arn
  }}
}}

resource "aws_lb_listener" "{project}_{safe}_http_redirect" {{
  load_balancer_arn = aws_lb.{project}_{safe}.arn
  port              = "80"
  protocol          = "HTTP"

  default_action {{
    type = "redirect"
    redirect {{
      port        = "443"
      protocol    = "HTTPS"
      status_code = "HTTP_301"
    }}
  }}
}}

resource "aws_lb_target_group" "{project}_{safe}_tg" {{
  name        = "${{var.project_name}}-tg"
  port        = 3000
  protocol    = "HTTP"
  vpc_id      = aws_vpc.{project}_vpc.id
  target_type = "ip"

  health_check {{
    enabled             = true
    healthy_threshold   = 3
    interval            = 30
    matcher             = "200"
    path                = "/health"
    port                = "traffic-port"
    timeout             = 5
    unhealthy_threshold = 3
  }}
}}
"""

    def _gen_cloudfront(
        self,
        comp: Component,
        spec: RequirementsSpec,
        project: str,
        safe: str,
        lb_safe: str | None = None,
    ) -> str:
        # Resolve the ALB resource name dynamically; fall back to a conventional name
        alb_ref = f"aws_lb.{project}_{lb_safe}" if lb_safe else f"aws_lb.{project}_alb"
        return f"""\
# Generated by FaultRay Autopilot — CloudFront

resource "aws_cloudfront_distribution" "{project}_{safe}" {{
  enabled             = true
  is_ipv6_enabled     = true
  default_root_object = "index.html"
  price_class         = "PriceClass_All"

  origin {{
    domain_name = {alb_ref}.dns_name
    origin_id   = "alb"

    custom_origin_config {{
      http_port              = 80
      https_port             = 443
      origin_protocol_policy = "https-only"
      origin_ssl_protocols   = ["TLSv1.2"]
    }}
  }}

  default_cache_behavior {{
    allowed_methods        = ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "alb"
    viewer_protocol_policy = "redirect-to-https"
    compress               = true

    forwarded_values {{
      query_string = true
      cookies {{
        forward = "all"
      }}
    }}

    min_ttl     = 0
    default_ttl = 3600
    max_ttl     = 86400
  }}

  restrictions {{
    geo_restriction {{
      restriction_type = "none"
    }}
  }}

  viewer_certificate {{
    cloudfront_default_certificate = true
  }}

  tags = {{
    Name = "${{var.project_name}}-cdn"
  }}
}}
"""

    def _gen_rds(
        self, comp: Component, spec: RequirementsSpec, project: str, safe: str
    ) -> str:
        multi_az = "true" if spec.multi_az else "false"
        engine = "postgres"
        engine_version = "16.1"
        port = 5432

        # Detect MySQL
        if any(tag in comp.tags for tag in ["mysql", "rds_mysql"]):
            engine = "mysql"
            engine_version = "8.0"
            port = 3306

        return f"""\
# Generated by FaultRay Autopilot — RDS

resource "aws_db_instance" "{project}_{safe}" {{
  identifier        = "${{var.project_name}}-{safe}"
  engine            = "{engine}"
  engine_version    = "{engine_version}"
  instance_class    = var.db_instance_class
  allocated_storage = 100
  storage_type      = "gp3"
  storage_encrypted = true

  db_name  = replace(var.project_name, "-", "_")
  username = "${{var.project_name}}_admin"
  password = random_password.{safe}_password.result

  vpc_security_group_ids = [aws_security_group.{project}_db_sg.id]
  db_subnet_group_name   = aws_db_subnet_group.{project}_db_subnet_group.name

  multi_az               = {multi_az}
  publicly_accessible    = false
  deletion_protection    = true
  skip_final_snapshot    = false
  final_snapshot_identifier = "${{var.project_name}}-{safe}-final"

  backup_retention_period = 7
  backup_window           = "03:00-04:00"
  maintenance_window      = "Mon:04:00-Mon:05:00"

  performance_insights_enabled          = true
  performance_insights_retention_period = 7
  monitoring_interval                   = 60

  auto_minor_version_upgrade = true

  tags = {{
    Name = "${{var.project_name}}-{safe}"
  }}
}}

resource "random_password" "{safe}_password" {{
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+[]:?"
}}

resource "aws_secretsmanager_secret" "{safe}_credentials" {{
  name                    = "${{var.project_name}}/{safe}/credentials"
  recovery_window_in_days = 7
}}

resource "aws_secretsmanager_secret_version" "{safe}_credentials_version" {{
  secret_id = aws_secretsmanager_secret.{safe}_credentials.id
  secret_string = jsonencode({{
    username = aws_db_instance.{project}_{safe}.username
    password = random_password.{safe}_password.result
    host     = aws_db_instance.{project}_{safe}.address
    port     = {port}
    dbname   = aws_db_instance.{project}_{safe}.db_name
  }})
}}
"""

    def _gen_elasticache(
        self, comp: Component, spec: RequirementsSpec, project: str, safe: str
    ) -> str:
        num_cache_nodes = 2 if spec.multi_az else 1

        return f"""\
# Generated by FaultRay Autopilot — ElastiCache Redis

resource "aws_elasticache_subnet_group" "{project}_{safe}_subnet_group" {{
  name       = "${{var.project_name}}-cache-subnet-group"
  subnet_ids = aws_subnet.{project}_private[*].id
}}

resource "aws_elasticache_replication_group" "{project}_{safe}" {{
  replication_group_id = "${{var.project_name}}-cache"
  description          = "Redis cluster for ${{var.project_name}}"

  node_type               = "cache.t3.medium"
  num_cache_clusters      = {num_cache_nodes}
  parameter_group_name    = "default.redis7"
  port                    = 6379
  engine_version          = "7.1"

  subnet_group_name  = aws_elasticache_subnet_group.{project}_{safe}_subnet_group.name
  security_group_ids = [aws_security_group.{project}_cache_sg.id]

  at_rest_encryption_enabled = true
  transit_encryption_enabled = true

  automatic_failover_enabled = {"true" if spec.multi_az else "false"}
  multi_az_enabled           = {"true" if spec.multi_az else "false"}

  tags = {{
    Name = "${{var.project_name}}-cache"
  }}
}}
"""

    def _gen_ecs(
        self,
        comp: Component,
        spec: RequirementsSpec,
        project: str,
        safe: str,
        db_safe: str | None = None,
        lb_safe: str | None = None,
    ) -> str:
        min_capacity = comp.autoscaling.min_replicas if comp.autoscaling.enabled else 1
        max_capacity = comp.autoscaling.max_replicas if comp.autoscaling.enabled else 2

        # Build secrets block dynamically — only include if a DB component exists
        if db_safe is not None:
            secrets_block = f"""\
      secrets = [
        {{
          name      = "DATABASE_URL"
          valueFrom = aws_secretsmanager_secret.{db_safe}_credentials.arn
        }}
      ]"""
        else:
            secrets_block = "      secrets = []"

        # Build load_balancer block dynamically — only include if an LB component exists
        if lb_safe is not None:
            lb_block = f"""\
  load_balancer {{
    target_group_arn = aws_lb_target_group.{project}_{lb_safe}_tg.arn
    container_name   = "{safe}"
    container_port   = 3000
  }}
"""
        else:
            lb_block = ""

        return f"""\
# Generated by FaultRay Autopilot — ECS Fargate

resource "aws_ecs_cluster" "{project}_{safe}_cluster" {{
  name = "${{var.project_name}}-{safe}-cluster"

  setting {{
    name  = "containerInsights"
    value = "enabled"
  }}
}}

resource "aws_ecs_task_definition" "{project}_{safe}_task" {{
  family                   = "${{var.project_name}}-{safe}"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "512"
  memory                   = "1024"
  execution_role_arn       = aws_iam_role.{project}_ecs_execution_role.arn
  task_role_arn            = aws_iam_role.{project}_ecs_task_role.arn

  container_definitions = jsonencode([
    {{
      name      = "{safe}"
      image     = "${{var.project_name}}/{safe}:latest"
      essential = true

      portMappings = [
        {{
          containerPort = 3000
          hostPort      = 3000
          protocol      = "tcp"
        }}
      ]

      environment = []

{secrets_block}

      logConfiguration = {{
        logDriver = "awslogs"
        options = {{
          "awslogs-group"         = "/ecs/${{var.project_name}}/{safe}"
          "awslogs-region"        = var.aws_region
          "awslogs-stream-prefix" = "ecs"
        }}
      }}

      healthCheck = {{
        command     = ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
        interval    = 30
        timeout     = 5
        retries     = 3
        startPeriod = 60
      }}
    }}
  ])
}}

resource "aws_ecs_service" "{project}_{safe}_service" {{
  name            = "${{var.project_name}}-{safe}-service"
  cluster         = aws_ecs_cluster.{project}_{safe}_cluster.id
  task_definition = aws_ecs_task_definition.{project}_{safe}_task.arn
  desired_count   = {min_capacity}
  launch_type     = "FARGATE"

  network_configuration {{
    subnets          = aws_subnet.{project}_private[*].id
    security_groups  = [aws_security_group.{project}_app_sg.id]
    assign_public_ip = false
  }}

{lb_block}
  deployment_configuration {{
    maximum_percent         = 200
    minimum_healthy_percent = 100
  }}

  deployment_circuit_breaker {{
    enable   = true
    rollback = true
  }}

  lifecycle {{
    ignore_changes = [desired_count]
  }}
}}

resource "aws_cloudwatch_log_group" "{project}_{safe}_logs" {{
  name              = "/ecs/${{var.project_name}}/{safe}"
  retention_in_days = 30
}}

# Auto Scaling
resource "aws_appautoscaling_target" "{project}_{safe}_scaling_target" {{
  max_capacity       = {max_capacity}
  min_capacity       = {min_capacity}
  resource_id        = "service/${{aws_ecs_cluster.{project}_{safe}_cluster.name}}/${{aws_ecs_service.{project}_{safe}_service.name}}"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"
}}

resource "aws_appautoscaling_policy" "{project}_{safe}_cpu_scaling" {{
  name               = "${{var.project_name}}-{safe}-cpu-scaling"
  policy_type        = "TargetTrackingScaling"
  resource_id        = aws_appautoscaling_target.{project}_{safe}_scaling_target.resource_id
  scalable_dimension = aws_appautoscaling_target.{project}_{safe}_scaling_target.scalable_dimension
  service_namespace  = aws_appautoscaling_target.{project}_{safe}_scaling_target.service_namespace

  target_tracking_scaling_policy_configuration {{
    predefined_metric_specification {{
      predefined_metric_type = "ECSServiceAverageCPUUtilization"
    }}
    target_value       = 70.0
    scale_in_cooldown  = 300
    scale_out_cooldown = 60
  }}
}}
"""

    def _gen_iam(self, project: str) -> str:
        """Generate shared IAM roles for ECS (generated once, not per service)."""
        return f"""\
# Generated by FaultRay Autopilot — IAM Roles (shared by all ECS services)

resource "aws_iam_role" "{project}_ecs_execution_role" {{
  name = "${{var.project_name}}-ecs-execution-role"

  assume_role_policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [
      {{
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {{
          Service = "ecs-tasks.amazonaws.com"
        }}
      }}
    ]
  }})
}}

resource "aws_iam_role_policy_attachment" "{project}_ecs_execution_role_policy" {{
  role       = aws_iam_role.{project}_ecs_execution_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}}

resource "aws_iam_role" "{project}_ecs_task_role" {{
  name = "${{var.project_name}}-ecs-task-role"

  assume_role_policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [
      {{
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {{
          Service = "ecs-tasks.amazonaws.com"
        }}
      }}
    ]
  }})
}}
"""

    def _gen_s3_frontend(
        self, comp: Component, spec: RequirementsSpec, project: str, safe: str
    ) -> str:
        return f"""\
# Generated by FaultRay Autopilot — S3 Static Frontend

resource "aws_s3_bucket" "{project}_{safe}" {{
  bucket = "${{var.project_name}}-frontend"
}}

resource "aws_s3_bucket_versioning" "{project}_{safe}_versioning" {{
  bucket = aws_s3_bucket.{project}_{safe}.id
  versioning_configuration {{
    status = "Enabled"
  }}
}}

resource "aws_s3_bucket_public_access_block" "{project}_{safe}_pab" {{
  bucket = aws_s3_bucket.{project}_{safe}.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}}

resource "aws_s3_bucket_server_side_encryption_configuration" "{project}_{safe}_sse" {{
  bucket = aws_s3_bucket.{project}_{safe}.id

  rule {{
    apply_server_side_encryption_by_default {{
      sse_algorithm = "AES256"
    }}
  }}
}}
"""

    def _gen_sqs(
        self, comp: Component, spec: RequirementsSpec, project: str, safe: str
    ) -> str:
        return f"""\
# Generated by FaultRay Autopilot — SQS Queue

resource "aws_sqs_queue" "{project}_{safe}_dlq" {{
  name                      = "${{var.project_name}}-{safe}-dlq"
  message_retention_seconds = 1209600  # 14 days

  tags = {{
    Name = "${{var.project_name}}-{safe}-dlq"
  }}
}}

resource "aws_sqs_queue" "{project}_{safe}" {{
  name                       = "${{var.project_name}}-{safe}"
  visibility_timeout_seconds = 300
  message_retention_seconds  = 86400
  receive_wait_time_seconds  = 20

  redrive_policy = jsonencode({{
    deadLetterTargetArn = aws_sqs_queue.{project}_{safe}_dlq.arn
    maxReceiveCount     = 3
  }})

  tags = {{
    Name = "${{var.project_name}}-{safe}"
  }}
}}
"""

    def _gen_s3(
        self, comp: Component, spec: RequirementsSpec, project: str, safe: str
    ) -> str:
        return f"""\
# Generated by FaultRay Autopilot — S3 Storage

resource "aws_s3_bucket" "{project}_{safe}" {{
  bucket = "${{var.project_name}}-{safe}"
}}

resource "aws_s3_bucket_versioning" "{project}_{safe}_versioning" {{
  bucket = aws_s3_bucket.{project}_{safe}.id
  versioning_configuration {{
    status = "Enabled"
  }}
}}

resource "aws_s3_bucket_server_side_encryption_configuration" "{project}_{safe}_sse" {{
  bucket = aws_s3_bucket.{project}_{safe}.id

  rule {{
    apply_server_side_encryption_by_default {{
      sse_algorithm = "AES256"
    }}
  }}
}}

resource "aws_s3_bucket_public_access_block" "{project}_{safe}_pab" {{
  bucket = aws_s3_bucket.{project}_{safe}.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}}
"""
