# Copyright (c) 2025-2026 Yutaro Maeda. All rights reserved.
# Licensed under the Apache License 2.0. See LICENSE file for details.

"""Badge API endpoint — serves resilience score badges as SVG/redirect.

Provides a ``/badge/{badge_type}.svg`` endpoint that returns an SVG badge
generated by :class:`~faultray.api.badge_generator.BadgeGenerator`, and a
``/badge/{badge_type}/shields`` endpoint that redirects to a shields.io
dynamic badge URL.
"""

from __future__ import annotations

import logging

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import RedirectResponse, Response

from faultray.api.badge_generator import BadgeGenerator, BadgeStyle, BadgeType
from faultray.api.routes._shared import get_graph

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/badge", tags=["badge"])


def _resolve_badge_type(name: str) -> BadgeType:
    """Resolve a badge type string to the enum, raising 404 on mismatch."""
    # Strip trailing `.svg` if present
    clean = name.removesuffix(".svg")
    try:
        return BadgeType(clean)
    except ValueError:
        raise HTTPException(status_code=404, detail=f"Unknown badge type: {clean}")


@router.get("/{badge_name}.svg")
async def badge_svg(
    badge_name: str,
    style: BadgeStyle = Query(BadgeStyle.FLAT, description="Badge visual style"),
) -> Response:
    """Return an SVG badge for the given metric.

    Example: ``GET /badge/resilience_score.svg?style=flat``
    """
    badge_type = _resolve_badge_type(badge_name)
    graph = get_graph()
    if graph is None:
        raise HTTPException(status_code=503, detail="No infrastructure model loaded")

    gen = BadgeGenerator()
    if badge_type == BadgeType.RESILIENCE_SCORE:
        svg = gen.generate_resilience_badge(graph, style)
    elif badge_type == BadgeType.SLA_ESTIMATE:
        svg = gen.generate_sla_badge(graph, style)
    elif badge_type == BadgeType.GRADE:
        svg = gen.generate_grade_badge(graph, style)
    elif badge_type == BadgeType.SPOF_COUNT:
        svg = gen.generate_spof_badge(graph, style)
    else:
        svg = gen.generate_svg(badge_type, "n/a", "#999", style)

    return Response(
        content=svg,
        media_type="image/svg+xml",
        headers={
            "Cache-Control": "no-cache, no-store, must-revalidate",
            "Pragma": "no-cache",
        },
    )


@router.get("/{badge_name}/shields")
async def badge_shields_redirect(
    badge_name: str,
) -> RedirectResponse:
    """Redirect to a shields.io badge URL for the given metric.

    Example: ``GET /badge/resilience_score/shields`` -> 302 to shields.io
    """
    badge_type = _resolve_badge_type(badge_name)
    graph = get_graph()
    if graph is None:
        raise HTTPException(status_code=503, detail="No infrastructure model loaded")

    score = round(graph.resilience_score(), 1)

    if badge_type == BadgeType.RESILIENCE_SCORE:
        label = "resilience"
        value = f"{int(score)}%2F100"
        color = _shields_color(score)
    elif badge_type == BadgeType.GRADE:
        from faultray.api.badge_generator import _score_to_grade

        label = "grade"
        value = _score_to_grade(score)
        color = _shields_color(score)
    else:
        label = badge_name.removesuffix(".svg").replace("_", "%20")
        value = str(int(score))
        color = _shields_color(score)

    url = f"https://img.shields.io/badge/{label}-{value}-{color}"
    return RedirectResponse(url=url, status_code=302)


def _shields_color(score: float) -> str:
    """Map a 0-100 score to a shields.io named color."""
    if score >= 80:
        return "brightgreen"
    if score >= 60:
        return "green"
    if score >= 40:
        return "yellow"
    if score >= 20:
        return "orange"
    return "red"
